CREATE DATABASE leads_db;

SELECT *
	FROM public.lead
 ORDER BY id;
	
ALTER TABLE lead ADD COLUMN status VARCHAR(50) DEFAULT 'Novo Lead';
ALTER TABLE lead ADD COLUMN data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
